- name: Restart RocketChat
  community.docker.docker_compose_v2:
    project_src: /opt/rocketchat/
    files:
      - compose.database.yml
      - compose.monitoring.yml
      - compose.yml
    state: restarted
