name: Build and Push Ansible image
trigger: none

steps:
  - task: Docker@2
    displayName: Login to Container Registry
    inputs:
      command: Login
      containerRegistry: $(containerRegistry)

  - task: CmdLine@2
    displayName: Create Build Context
    inputs:
      script: |
        ansible-builder create

  - task: Docker@2
    inputs:
      command: 'buildAndPush'
      Dockerfile: 'context/Dockerfile'
      buildContext: '$(Build.Repository.LocalPath)/context'
      repository: $(containerRepository)
