name: Provision Infrastructure
trigger: none

steps:
  - task: CmdLine@2
    displayName: Group Vars Environment Substitution
    inputs:
      script: |
        touch empty.cfg
        envsubst < ./group_vars/all.yaml.tmpl > ./group_vars/all.yaml
    env:
      ADMIN_PUBKEY: $(id_agentkey.pub)
      RESOURCE_PREFIX: $(resourcePrefix)
        
  - task: CmdLine@2
    displayName: Provision
    inputs:
      script: |
        set -x
        echo $(pwd)
        ls -la $(Build.SourcesDirectory)
        CONTAINER_ID=$(docker create \
          -e ANSIBLE_CONFIG='empty.cfg' -e AZURE_SUBSCRIPTION_ID=$(AZURE_SUBSCRIPTION_ID) \
          -e AZURE_CLIENT_ID=$(AZURE_CLIENT_ID) -e AZURE_SECRET=$(AZURE_SECRET) -e AZURE_TENANT=$(AZURE_TENANT) \
          $(containerImageName) ansible-playbook provision.yaml --diff)
        docker cp "$(Build.SourcesDirectory)/." "$CONTAINER_ID":/runner
        docker start -ai "$CONTAINER_ID"
        docker rm "$CONTAINER_ID"
