- name: Clone Compose Repository
  ansible.builtin.git:
    repo: https://github.com/RocketChat/rocketchat-compose.git
    dest: /opt/rocketchat/
    depth: 1

- name: RocketChat .env
  ansible.builtin.template:
    src: .env.j2
    dest: /opt/rocketchat/.env
  notify: Restart RocketChat

- name: RocketChat Compose Up
  community.docker.docker_compose_v2:
    project_src: /opt/rocketchat/
    files:
      - compose.database.yml
      - compose.monitoring.yml
      - compose.yml
